name: kuluk_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  contacts_service: ^0.6.3
  flutter_contacts: ^1.1.2
  url_launcher: ^6.0.18
  sqflite: ^2.0.2
  path_provider: ^2.0.8
#  package_info_plus: ^1.3.0
#  fluttercontactpicker: ^4.6.0
  fluttertoast: ^8.0.8
  shake: ^2.0.0
  bottom_bar: ^1.3.0+1
  audioplayers: ^0.20.1
  sensors_plus: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

